apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-dev
  namespace: vegan
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: api-service-dev
  template:
    metadata:
      labels:
        app: api-service-dev
    spec:
      containers:
        - name: api-service-dev
          image: harbor.kyojs.com/vegan/api-server-dev:614a512c
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 3200
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3200
            initialDelaySeconds: 10
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: 3200
            failureThreshold: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 1Gi
          ports:
            - containerPort: 3200
          envFrom:
            - secretRef:
                name: api-server-dev

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-service-dev
  namespace: vegan
spec:
  maxReplicas: 6
  minReplicas: 2
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 65
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-service-dev
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-db
  namespace: vegan
spec:
  type: ExternalName
  externalName: kyojs.synology.me
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-dev-lb
  namespace: vegan
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: api-service-dev
  ports:
    - name: api-server-dev
      protocol: TCP
      port: 3201
      targetPort: 3200
